var classes = [
    {
        "name": "IceHawk\\Forms\\Exceptions\\FormsException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.16,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Exceptions\\InvalidExpiryInterval",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Exceptions\\FormsException",
            "IceHawk\\Forms\\Exceptions\\InvalidExpiryInterval"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 102.12,
        "mIwoC": 66.43,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Exceptions\\InvalidTokenString",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Exceptions\\FormsException",
            "IceHawk\\Forms\\Exceptions\\InvalidTokenString"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 102.12,
        "mIwoC": 66.43,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Exceptions\\TokenHasExpired",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Exceptions\\FormsException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Exceptions\\TokenMismatch",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Exceptions\\FormsException",
            "IceHawk\\Forms\\Exceptions\\TokenMismatch",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource"
        ],
        "lcom": 1,
        "length": 14,
        "vocabulary": 5,
        "volume": 32.51,
        "difficulty": 3,
        "effort": 97.52,
        "level": 0.33,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 10.84,
        "number_operators": 5,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 26,
        "lloc": 20,
        "mi": 94.77,
        "mIwoC": 60.9,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.67,
        "relativeSystemComplexity": 3.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 11,
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 7,
        "instability": 0.7,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Feedback",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\ProvidesFeedback"
        ],
        "lcom": 1,
        "length": 22,
        "vocabulary": 10,
        "volume": 73.08,
        "difficulty": 2.13,
        "effort": 155.3,
        "level": 0.47,
        "bugs": 0.02,
        "time": 9,
        "intelligentContent": 34.39,
        "number_operators": 5,
        "number_operands": 17,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 6,
        "loc": 34,
        "lloc": 28,
        "mi": 85.54,
        "mIwoC": 55.25,
        "commentWeight": 30.29,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 14,
        "totalSystemComplexity": 14,
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Form",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 23,
        "nbMethods": 21,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 21,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\ProvidesFormData",
            "IceHawk\\Forms\\Interfaces\\IdentifiesForm",
            "IceHawk\\Forms\\Interfaces\\IdentifiesForm",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Security\\Token",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Exceptions\\TokenMismatch",
            "IceHawk\\Forms\\Exceptions\\TokenHasExpired",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Interfaces\\ProvidesFeedback",
            "IceHawk\\Forms\\Interfaces\\ProvidesFeedback",
            "IceHawk\\Forms\\Feedback"
        ],
        "lcom": 1,
        "length": 120,
        "vocabulary": 17,
        "volume": 490.5,
        "difficulty": 23.18,
        "effort": 11370.58,
        "level": 0.04,
        "bugs": 0.16,
        "time": 632,
        "intelligentContent": 21.16,
        "number_operators": 35,
        "number_operands": 85,
        "number_operators_unique": 6,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 133,
        "lloc": 124,
        "mi": 54.16,
        "mIwoC": 34.55,
        "commentWeight": 19.61,
        "kanDefect": 0.73,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 1.74,
        "relativeSystemComplexity": 65.74,
        "totalStructuralComplexity": 1472,
        "totalDataComplexity": 40.11,
        "totalSystemComplexity": 1512.11,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\FormId",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\IdentifiesForm"
        ],
        "lcom": 1,
        "length": 10,
        "vocabulary": 4,
        "volume": 20,
        "difficulty": 3,
        "effort": 60,
        "level": 0.33,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 6.67,
        "number_operators": 4,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 26,
        "lloc": 21,
        "mi": 93.33,
        "mIwoC": 61.91,
        "commentWeight": 31.42,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 2.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 6.5,
        "totalSystemComplexity": 10.5,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Interfaces\\Identifies",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "JsonSerializable"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.23,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Interfaces\\IdentifiesForm",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\Identifies"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.05,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\Identifies",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.2,
        "afferentCoupling": 12,
        "efferentCoupling": 3,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Interfaces\\ProvidesFeedback",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "JsonSerializable"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.05,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Interfaces\\ProvidesFormData",
        "interface": true,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "JsonSerializable"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\Forms\\Security\\Token",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "externals": [
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "IceHawk\\Forms\\Security\\Token",
            "DateTimeImmutable",
            "IceHawk\\Forms\\Exceptions\\InvalidExpiryInterval",
            "IceHawk\\Forms\\Interfaces\\IdentifiesFormRequestSource",
            "DateTimeImmutable",
            "IceHawk\\Forms\\Security\\Token",
            "self",
            "DateTimeImmutable",
            "IceHawk\\Forms\\Exceptions\\InvalidTokenString"
        ],
        "lcom": 2,
        "length": 75,
        "vocabulary": 21,
        "volume": 329.42,
        "difficulty": 11,
        "effort": 3623.66,
        "level": 0.09,
        "bugs": 0.11,
        "time": 201,
        "intelligentContent": 29.95,
        "number_operators": 31,
        "number_operands": 44,
        "number_operators_unique": 7,
        "number_operands_unique": 14,
        "cloc": 6,
        "loc": 71,
        "lloc": 65,
        "mi": 63.65,
        "mIwoC": 41.88,
        "commentWeight": 21.76,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.56,
        "relativeSystemComplexity": 26.56,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 12.5,
        "totalSystemComplexity": 212.5,
        "pageRank": 0.03,
        "afferentCoupling": 5,
        "efferentCoupling": 12,
        "instability": 0.71,
        "violations": {}
    }
];
