var classes = [
    {
        "name": "IceHawk\\PubSub\\AbstractMessageSubscriber",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\SubscribesToMessages",
            "IceHawk\\PubSub\\Interfaces\\CarriesInformation",
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\NamesMessage"
        ],
        "lcom": 1,
        "length": 32,
        "vocabulary": 17,
        "volume": 130.8,
        "difficulty": 3.85,
        "effort": 503.07,
        "level": 0.26,
        "bugs": 0.04,
        "time": 28,
        "intelligentContent": 34.01,
        "number_operators": 7,
        "number_operands": 25,
        "number_operators_unique": 4,
        "number_operands_unique": 13,
        "cloc": 4,
        "loc": 23,
        "lloc": 19,
        "mi": 87.12,
        "mIwoC": 57.02,
        "commentWeight": 30.1,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Exceptions\\PubSubException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\CarriesInformation",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\IdentifiesMessage",
            "IceHawk\\PubSub\\Interfaces\\NamesMessage"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.07,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\DispatchesMessages",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\PublishesMessages",
            "IceHawk\\PubSub\\Interfaces\\RegistersChannelSubscribers"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\RepresentsValueAsString"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.12,
        "afferentCoupling": 8,
        "efferentCoupling": 1,
        "instability": 0.11,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\IdentifiesMessage",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\RepresentsValueAsString"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.09,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\NamesMessage",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\RepresentsValueAsString"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.09,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\PublishesMessages",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\CarriesInformation"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\RegistersChannelSubscribers",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\SubscribesToMessages"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\RepresentsValueAsString",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "JsonSerializable"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.41,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Interfaces\\SubscribesToMessages",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\CarriesInformation",
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.04,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\MessageBus",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\DispatchesMessages",
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\CarriesInformation",
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel",
            "IceHawk\\PubSub\\Interfaces\\SubscribesToMessages"
        ],
        "lcom": 1,
        "length": 38,
        "vocabulary": 10,
        "volume": 126.23,
        "difficulty": 9.67,
        "effort": 1220.25,
        "level": 0.1,
        "bugs": 0.04,
        "time": 68,
        "intelligentContent": 13.06,
        "number_operators": 9,
        "number_operands": 29,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 11,
        "loc": 42,
        "lloc": 31,
        "mi": 87.83,
        "mIwoC": 52.22,
        "commentWeight": 35.62,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.56,
        "relativeSystemComplexity": 9.56,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 2.25,
        "totalSystemComplexity": 38.25,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Types\\Channel",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\IdentifiesChannel"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 102.99,
        "mIwoC": 67.31,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Types\\MessageId",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\IdentifiesMessage"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 102.99,
        "mIwoC": 67.31,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\PubSub\\Types\\MessageName",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\PubSub\\Interfaces\\NamesMessage"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 102.99,
        "mIwoC": 67.31,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
];
