var classes = [
    {
        "name": "IceHawk\\Session\\AbstractSession",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 8,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 10,
        "externals": [
            "IceHawk\\Session\\Interfaces\\MapsSessionData",
            "IceHawk\\Session\\Interfaces\\MapsSessionData",
            "IceHawk\\Session\\Interfaces\\MapsSessionData"
        ],
        "lcom": 1,
        "length": 115,
        "vocabulary": 14,
        "volume": 437.85,
        "difficulty": 17.6,
        "effort": 7706.09,
        "level": 0.06,
        "bugs": 0.15,
        "time": 428,
        "intelligentContent": 24.88,
        "number_operators": 27,
        "number_operands": 88,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 10,
        "loc": 96,
        "lloc": 86,
        "mi": 61.93,
        "mIwoC": 37.96,
        "commentWeight": 23.97,
        "kanDefect": 1.65,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 49.78,
        "totalStructuralComplexity": 539,
        "totalDataComplexity": 8.63,
        "totalSystemComplexity": 547.63,
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\Session\\Exceptions\\SessionException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.17,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\Session\\Interfaces\\MapsSessionData",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.66,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
];
