var classes = [
    {
        "name": "IceHawk\\IceHawk\\Config\\ConfigGuard",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
            "IceHawk\\IceHawk\\Exceptions\\InvalidEventSubscriberCollection"
        ],
        "lcom": 1,
        "length": 19,
        "vocabulary": 9,
        "volume": 60.23,
        "difficulty": 5.2,
        "effort": 313.19,
        "level": 0.19,
        "bugs": 0.02,
        "time": 17,
        "intelligentContent": 11.58,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 14,
        "loc": 37,
        "lloc": 23,
        "mi": 98.32,
        "mIwoC": 57.56,
        "commentWeight": 40.76,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 9.33,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 28,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Config\\ConfigWrapper",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToReadRequest",
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToWriteRequest"
        ],
        "lcom": 1,
        "length": 52,
        "vocabulary": 6,
        "volume": 134.42,
        "difficulty": 27,
        "effort": 3629.29,
        "level": 0.04,
        "bugs": 0.04,
        "time": 202,
        "intelligentContent": 4.98,
        "number_operators": 25,
        "number_operands": 27,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 20,
        "loc": 77,
        "lloc": 57,
        "mi": 81.35,
        "mIwoC": 45.85,
        "commentWeight": 35.5,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 36.88,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 6.14,
        "totalSystemComplexity": 258.14,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Constants\\HandlerMethodInterfaceMap",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 9,
        "lloc": 5,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Constants\\HttpCode",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 74,
        "vocabulary": 74,
        "volume": 459.5,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.15,
        "time": 0,
        "intelligentContent": 919,
        "number_operators": 0,
        "number_operands": 74,
        "number_operators_unique": 0,
        "number_operands_unique": 74,
        "cloc": 4,
        "loc": 82,
        "lloc": 78,
        "mi": 56.73,
        "mIwoC": 39.95,
        "commentWeight": 16.78,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Constants\\HttpMethod",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 4,
        "loc": 18,
        "lloc": 14,
        "mi": 99.16,
        "mIwoC": 65.81,
        "commentWeight": 33.35,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Defaults\\FinalReadResponder",
        "interface": false,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToReadRequest",
            "Throwable",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 4,
        "loc": 12,
        "lloc": 8,
        "mi": 115.82,
        "mIwoC": 76.82,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Defaults\\FinalWriteResponder",
        "interface": false,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToWriteRequest",
            "Throwable",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 4,
        "loc": 12,
        "lloc": 8,
        "mi": 115.82,
        "mIwoC": 76.82,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Defaults\\IceHawkConfig",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 14,
        "lloc": 10,
        "mi": 207.83,
        "mIwoC": 171,
        "commentWeight": 36.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Defaults\\IceHawkDelegate",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\SetsUpEnvironment",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "lcom": 3,
        "length": 2,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 4,
        "loc": 17,
        "lloc": 13,
        "mi": 205.14,
        "mIwoC": 171,
        "commentWeight": 34.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 0.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Defaults\\RequestInfo",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 18,
        "nbMethods": 17,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 16,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 4,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "self"
        ],
        "lcom": 2,
        "length": 97,
        "vocabulary": 33,
        "volume": 489.31,
        "difficulty": 5.98,
        "effort": 2927.1,
        "level": 0.17,
        "bugs": 0.16,
        "time": 163,
        "intelligentContent": 81.79,
        "number_operators": 30,
        "number_operands": 67,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 13,
        "loc": 105,
        "lloc": 92,
        "mi": 63.72,
        "mIwoC": 37.79,
        "commentWeight": 25.93,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 10.06,
        "relativeSystemComplexity": 11.06,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 181,
        "totalSystemComplexity": 199,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\HandlingReadRequestEvent",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 98.25,
        "mIwoC": 64.59,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\HandlingWriteRequestEvent",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 98.25,
        "mIwoC": 64.59,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\IceHawkWasInitializedEvent",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 18,
        "lloc": 13,
        "mi": 104.45,
        "mIwoC": 68.01,
        "commentWeight": 36.44,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\InitializingIceHawkEvent",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 2,
        "effort": 24,
        "level": 0.5,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 6,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 18,
        "lloc": 13,
        "mi": 104.45,
        "mIwoC": 68.01,
        "commentWeight": 36.44,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\ReadRequestWasHandledEvent",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 98.25,
        "mIwoC": 64.59,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Events\\WriteRequestWasHandledEvent",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 98.25,
        "mIwoC": 64.59,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Exceptions\\IceHawkException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.05,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Exceptions\\InvalidEventSubscriberCollection",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Exceptions\\IceHawkException"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 13,
        "loc": 27,
        "lloc": 14,
        "mi": 110.41,
        "mIwoC": 66.43,
        "commentWeight": 43.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Exceptions\\UnresolvedRequest",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Exceptions\\IceHawkException",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 2,
        "effort": 41.79,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 10.45,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 101.3,
        "mIwoC": 65.62,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\IceHawk",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
            "IceHawk\\IceHawk\\Interfaces\\SetsUpEnvironment",
            "IceHawk\\IceHawk\\PubSub\\EventPublisher",
            "IceHawk\\IceHawk\\Config\\ConfigWrapper",
            "IceHawk\\IceHawk\\Events\\InitializingIceHawkEvent",
            "IceHawk\\IceHawk\\Events\\IceHawkWasInitializedEvent",
            "IceHawk\\IceHawk\\Config\\ConfigGuard",
            "IceHawk\\IceHawk\\RequestHandlers\\WriteRequestHandler",
            "IceHawk\\IceHawk\\RequestHandlers\\ReadRequestHandler",
            "IceHawk\\IceHawk\\RequestHandlers\\OptionsRequestHandler",
            "IceHawk\\IceHawk\\Responses\\MethodNotImplemented"
        ],
        "lcom": 1,
        "length": 62,
        "vocabulary": 11,
        "volume": 214.48,
        "difficulty": 9.19,
        "effort": 1970.58,
        "level": 0.11,
        "bugs": 0.07,
        "time": 109,
        "intelligentContent": 23.35,
        "number_operators": 13,
        "number_operands": 49,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 17,
        "loc": 70,
        "lloc": 53,
        "mi": 80.23,
        "mIwoC": 45.66,
        "commentWeight": 34.57,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.03,
        "relativeSystemComplexity": 169.03,
        "totalStructuralComplexity": 845,
        "totalDataComplexity": 0.14,
        "totalSystemComplexity": 845.14,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
        "interface": true,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToReadRequest",
            "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToWriteRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 6,
        "efferentCoupling": 3,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesDeleteRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesGetRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesHeadRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesHeadRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesReadRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesPatchRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesPostRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesPutRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesReadRequest",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesRequest",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesRequest",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\HandlesRequest",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 6,
        "efferentCoupling": 2,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 7,
        "efferentCoupling": 2,
        "instability": 0.22,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData",
        "interface": true,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInputData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 6,
        "efferentCoupling": 1,
        "instability": 0.14,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestData",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
        "interface": true,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.17,
        "afferentCoupling": 21,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInputData",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesUploadedFileData",
        "interface": true,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesUploadedFiles",
        "interface": true,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 7,
        "efferentCoupling": 2,
        "instability": 0.22,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInputData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesUploadedFiles"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.04,
        "afferentCoupling": 6,
        "efferentCoupling": 2,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToReadRequest",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Throwable",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\RespondsFinallyToWriteRequest",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Throwable",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Interfaces\\SetsUpEnvironment",
        "interface": true,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Mappers\\UploadedFilesMapper",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 6,
        "externals": [],
        "lcom": 1,
        "length": 50,
        "vocabulary": 18,
        "volume": 208.5,
        "difficulty": 4,
        "effort": 833.99,
        "level": 0.25,
        "bugs": 0.07,
        "time": 46,
        "intelligentContent": 52.12,
        "number_operators": 10,
        "number_operands": 40,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 14,
        "loc": 48,
        "lloc": 34,
        "mi": 86.67,
        "mIwoC": 49.55,
        "commentWeight": 37.12,
        "kanDefect": 1.14,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 2.17,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 6.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\AbstractEventSubscriber",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\SubscribesToEvents",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\PubSub\\Exceptions\\EventSubscriberMethodNotCallable"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 3.38,
        "effort": 256.86,
        "level": 0.3,
        "bugs": 0.03,
        "time": 14,
        "intelligentContent": 22.55,
        "number_operators": 4,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 9,
        "loc": 28,
        "lloc": 19,
        "mi": 97.15,
        "mIwoC": 58.66,
        "commentWeight": 38.48,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 9.42,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 28.25,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\EventPublisher",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\RegistersEventSubscribers",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\PublishesEvents",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\SubscribesToEvents",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData"
        ],
        "lcom": 1,
        "length": 17,
        "vocabulary": 5,
        "volume": 39.47,
        "difficulty": 4.33,
        "effort": 171.05,
        "level": 0.23,
        "bugs": 0.01,
        "time": 10,
        "intelligentContent": 9.11,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 28,
        "lloc": 23,
        "mi": 89.02,
        "mIwoC": 58.58,
        "commentWeight": 30.44,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 4.22,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 12.67,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Exceptions\\EventSubscriberMethodNotCallable",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Exceptions\\PubSubException"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 2,
        "effort": 41.79,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 10.45,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 4,
        "loc": 18,
        "lloc": 14,
        "mi": 98.97,
        "mIwoC": 65.62,
        "commentWeight": 33.35,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Exceptions\\PubSubException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Exceptions\\IceHawkException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.04,
        "afferentCoupling": 13,
        "efferentCoupling": 1,
        "instability": 0.07,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Interfaces\\PublishesEvents",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Interfaces\\RegistersEventSubscribers",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\SubscribesToEvents"
        ],
        "kanDefect": 0.15,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\PubSub\\Interfaces\\SubscribesToEvents",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\RequestHandlers\\AbstractRequestHandler",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ConfiguresIceHawk",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\PublishesEvents",
            "IceHawk\\IceHawk\\PubSub\\Interfaces\\CarriesEventData"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 5,
        "volume": 25.54,
        "difficulty": 1.13,
        "effort": 28.73,
        "level": 0.89,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 22.7,
        "number_operators": 2,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 104.73,
        "mIwoC": 63.75,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\RequestHandlers\\OptionsRequestHandler",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "IceHawk\\IceHawk\\RequestHandlers\\AbstractRequestHandler",
            "IceHawk\\IceHawk\\Responses\\Options",
            "IceHawk\\IceHawk\\Routing\\OptionsRouter",
            "IceHawk\\IceHawk\\Interfaces\\HandlesRequest"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 18,
        "volume": 266.88,
        "difficulty": 4.6,
        "effort": 1227.63,
        "level": 0.22,
        "bugs": 0.09,
        "time": 68,
        "intelligentContent": 58.02,
        "number_operators": 18,
        "number_operands": 46,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 9,
        "loc": 52,
        "lloc": 43,
        "mi": 76.88,
        "mIwoC": 46.84,
        "commentWeight": 30.04,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 121.38,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 1.92,
        "totalSystemComplexity": 606.92,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\RequestHandlers\\ReadRequestHandler",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\RequestHandlers\\AbstractRequestHandler",
            "IceHawk\\IceHawk\\Events\\HandlingReadRequestEvent",
            "IceHawk\\IceHawk\\Events\\ReadRequestWasHandledEvent",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler",
            "IceHawk\\IceHawk\\Routing\\RouteRequest",
            "IceHawk\\IceHawk\\Routing\\ReadRouter",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData",
            "IceHawk\\IceHawk\\Requests\\ReadRequestInput",
            "IceHawk\\IceHawk\\Requests\\ReadRequest"
        ],
        "lcom": 1,
        "length": 63,
        "vocabulary": 19,
        "volume": 267.62,
        "difficulty": 4.31,
        "effort": 1154.11,
        "level": 0.23,
        "bugs": 0.09,
        "time": 64,
        "intelligentContent": 62.06,
        "number_operators": 17,
        "number_operands": 46,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 12,
        "loc": 52,
        "lloc": 40,
        "mi": 81.79,
        "mIwoC": 47.92,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.15,
        "relativeSystemComplexity": 196.15,
        "totalStructuralComplexity": 784,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 784.6,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\RequestHandlers\\WriteRequestHandler",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\RequestHandlers\\AbstractRequestHandler",
            "IceHawk\\IceHawk\\Events\\HandlingWriteRequestEvent",
            "IceHawk\\IceHawk\\Events\\WriteRequestWasHandledEvent",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler",
            "IceHawk\\IceHawk\\Routing\\RouteRequest",
            "IceHawk\\IceHawk\\Routing\\WriteRouter",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData",
            "IceHawk\\IceHawk\\Requests\\WriteRequestInput",
            "IceHawk\\IceHawk\\Requests\\WriteRequest",
            "IceHawk\\IceHawk\\Mappers\\UploadedFilesMapper"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 25,
        "volume": 371.51,
        "difficulty": 3.95,
        "effort": 1469.15,
        "level": 0.25,
        "bugs": 0.12,
        "time": 82,
        "intelligentContent": 93.94,
        "number_operators": 22,
        "number_operands": 58,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 8,
        "loc": 58,
        "lloc": 51,
        "mi": 71.83,
        "mIwoC": 44.62,
        "commentWeight": 27.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 289.23,
        "totalStructuralComplexity": 1734,
        "totalDataComplexity": 1.39,
        "totalSystemComplexity": 1735.39,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 10,
        "instability": 0.91,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Requests\\ReadRequest",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 25,
        "lloc": 19,
        "mi": 96.26,
        "mIwoC": 61.85,
        "commentWeight": 34.41,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Requests\\ReadRequestInput",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesReadRequestInputData"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 7,
        "volume": 36.5,
        "difficulty": 3.38,
        "effort": 123.17,
        "level": 0.3,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 10.81,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 11,
        "loc": 28,
        "lloc": 17,
        "mi": 103.36,
        "mIwoC": 62.09,
        "commentWeight": 41.27,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Requests\\UploadedFile",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesUploadedFileData",
            "self",
            "finfo",
            "finfo"
        ],
        "lcom": 2,
        "length": 77,
        "vocabulary": 21,
        "volume": 338.21,
        "difficulty": 6.12,
        "effort": 2069.04,
        "level": 0.16,
        "bugs": 0.11,
        "time": 115,
        "intelligentContent": 55.28,
        "number_operators": 25,
        "number_operands": 52,
        "number_operators_unique": 4,
        "number_operands_unique": 17,
        "cloc": 9,
        "loc": 93,
        "lloc": 84,
        "mi": 63.35,
        "mIwoC": 40.18,
        "commentWeight": 23.17,
        "kanDefect": 0.37,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 5.27,
        "relativeSystemComplexity": 6.27,
        "totalStructuralComplexity": 11,
        "totalDataComplexity": 58,
        "totalSystemComplexity": 69,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Requests\\WriteRequest",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesRequestInfo",
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 6,
        "loc": 25,
        "lloc": 19,
        "mi": 96.26,
        "mIwoC": 61.85,
        "commentWeight": 34.41,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Requests\\WriteRequestInput",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Interfaces\\ProvidesWriteRequestInputData"
        ],
        "lcom": 1,
        "length": 41,
        "vocabulary": 13,
        "volume": 151.72,
        "difficulty": 4.2,
        "effort": 637.22,
        "level": 0.24,
        "bugs": 0.05,
        "time": 35,
        "intelligentContent": 36.12,
        "number_operators": 13,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 24,
        "loc": 62,
        "lloc": 38,
        "mi": 91.2,
        "mIwoC": 50.13,
        "commentWeight": 41.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.57,
        "relativeSystemComplexity": 4.57,
        "totalStructuralComplexity": 7,
        "totalDataComplexity": 25,
        "totalSystemComplexity": 32,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Responses\\AbstractHttpResponse",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [],
        "lcom": 1,
        "length": 35,
        "vocabulary": 13,
        "volume": 129.52,
        "difficulty": 3.9,
        "effort": 505.11,
        "level": 0.26,
        "bugs": 0.04,
        "time": 28,
        "intelligentContent": 33.21,
        "number_operators": 9,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 47,
        "lloc": 40,
        "mi": 78.14,
        "mIwoC": 49.99,
        "commentWeight": 28.14,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.48,
        "relativeSystemComplexity": 5.48,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 10.33,
        "totalSystemComplexity": 38.33,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Responses\\MethodNotImplemented",
        "interface": false,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Responses\\AbstractHttpResponse",
            "parent"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.75,
        "effort": 40.71,
        "level": 0.57,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.29,
        "number_operators": 2,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 100.98,
        "mIwoC": 65.29,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Responses\\Options",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Responses\\AbstractHttpResponse",
            "parent"
        ],
        "lcom": 2,
        "length": 11,
        "vocabulary": 8,
        "volume": 33,
        "difficulty": 2.1,
        "effort": 69.3,
        "level": 0.48,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 15.71,
        "number_operators": 4,
        "number_operands": 7,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 5,
        "loc": 23,
        "lloc": 18,
        "mi": 94.91,
        "mIwoC": 61.85,
        "commentWeight": 33.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 2.17,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 6.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\AbstractRouter",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Exceptions\\RoutesAreNotTraversable"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 9,
        "effort": 302.44,
        "level": 0.11,
        "bugs": 0.01,
        "time": 17,
        "intelligentContent": 3.73,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 4,
        "number_operands_unique": 2,
        "cloc": 16,
        "loc": 36,
        "lloc": 20,
        "mi": 103.6,
        "mIwoC": 60.66,
        "commentWeight": 42.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 1.83,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 5.5,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Exceptions\\RoutesAreNotTraversable",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Exceptions\\IceHawkException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 5,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.02,
        "afferentCoupling": 7,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToHandler",
        "interface": true,
        "methods": [
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "kanDefect": 0.15,
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToHandler"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler",
        "interface": true,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToHandler"
        ],
        "kanDefect": 0.15,
        "pageRank": 0.01,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\OptionsRouter",
        "interface": false,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\AbstractRouter"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 7,
        "volume": 36.5,
        "difficulty": 3.38,
        "effort": 123.17,
        "level": 0.3,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 10.81,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 9,
        "loc": 23,
        "lloc": 14,
        "mi": 104.87,
        "mIwoC": 63.66,
        "commentWeight": 41.22,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Patterns\\Literal",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 3,
        "effort": 77.55,
        "level": 0.33,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 8.62,
        "number_operators": 4,
        "number_operands": 6,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 96.8,
        "mIwoC": 63.13,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Patterns\\NamedRegExp",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult"
        ],
        "lcom": 1,
        "length": 36,
        "vocabulary": 14,
        "volume": 137.06,
        "difficulty": 5,
        "effort": 685.32,
        "level": 0.2,
        "bugs": 0.05,
        "time": 38,
        "intelligentContent": 27.41,
        "number_operators": 11,
        "number_operands": 25,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 9,
        "loc": 37,
        "lloc": 28,
        "mi": 87.52,
        "mIwoC": 52.93,
        "commentWeight": 34.59,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\Patterns\\RegExp",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult"
        ],
        "lcom": 1,
        "length": 45,
        "vocabulary": 18,
        "volume": 187.65,
        "difficulty": 9.55,
        "effort": 1791.17,
        "level": 0.1,
        "bugs": 0.06,
        "time": 100,
        "intelligentContent": 19.66,
        "number_operators": 15,
        "number_operands": 30,
        "number_operators_unique": 7,
        "number_operands_unique": 11,
        "cloc": 7,
        "loc": 36,
        "lloc": 29,
        "mi": 83.34,
        "mIwoC": 51.78,
        "commentWeight": 31.56,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\ReadRoute",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult",
            "IceHawk\\IceHawk\\Interfaces\\HandlesReadRequest",
            "IceHawk\\IceHawk\\Interfaces\\HandlesReadRequest"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 2.75,
        "effort": 113.74,
        "level": 0.36,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 15.04,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 6,
        "loc": 29,
        "lloc": 23,
        "mi": 91.23,
        "mIwoC": 58.84,
        "commentWeight": 32.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 5.25,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 21,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\ReadRouteGroup",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler"
        ],
        "lcom": 1,
        "length": 40,
        "vocabulary": 8,
        "volume": 120,
        "difficulty": 8.4,
        "effort": 1008,
        "level": 0.12,
        "bugs": 0.04,
        "time": 56,
        "intelligentContent": 14.29,
        "number_operators": 12,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 53,
        "lloc": 42,
        "mi": 81.79,
        "mIwoC": 49.36,
        "commentWeight": 32.43,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.97,
        "relativeSystemComplexity": 25.97,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 4.83,
        "totalSystemComplexity": 129.83,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\ReadRouter",
        "interface": false,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\AbstractRouter",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToReadHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo",
            "IceHawk\\IceHawk\\Exceptions\\UnresolvedRequest"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 9,
        "volume": 63.4,
        "difficulty": 5.6,
        "effort": 355.03,
        "level": 0.18,
        "bugs": 0.02,
        "time": 20,
        "intelligentContent": 11.32,
        "number_operators": 6,
        "number_operands": 14,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 28,
        "lloc": 18,
        "mi": 99.28,
        "mIwoC": 59.33,
        "commentWeight": 39.96,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\RouteRequest",
        "interface": false,
        "methods": [
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 16,
        "loc": 35,
        "lloc": 19,
        "mi": 105.16,
        "mIwoC": 61.85,
        "commentWeight": 43.31,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\WriteRoute",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult",
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest",
            "IceHawk\\IceHawk\\Interfaces\\HandlesWriteRequest"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 2.75,
        "effort": 113.74,
        "level": 0.36,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 15.04,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 6,
        "loc": 29,
        "lloc": 23,
        "mi": 91.23,
        "mIwoC": 58.84,
        "commentWeight": 32.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 5.25,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 21,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\WriteRouteGroup",
        "interface": false,
        "methods": [
            {},
            {},
            {},
            {},
            {}
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesMatchResult",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler"
        ],
        "lcom": 1,
        "length": 40,
        "vocabulary": 8,
        "volume": 120,
        "difficulty": 8.4,
        "effort": 1008,
        "level": 0.12,
        "bugs": 0.04,
        "time": 56,
        "intelligentContent": 14.29,
        "number_operators": 12,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 53,
        "lloc": 42,
        "mi": 81.79,
        "mIwoC": 49.36,
        "commentWeight": 32.43,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.97,
        "relativeSystemComplexity": 25.97,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 4.83,
        "totalSystemComplexity": 129.83,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "IceHawk\\IceHawk\\Routing\\WriteRouter",
        "interface": false,
        "methods": [
            {}
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "externals": [
            "IceHawk\\IceHawk\\Routing\\AbstractRouter",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\RoutesToWriteHandler",
            "IceHawk\\IceHawk\\Routing\\Interfaces\\ProvidesDestinationInfo",
            "IceHawk\\IceHawk\\Exceptions\\UnresolvedRequest"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 9,
        "volume": 63.4,
        "difficulty": 5.6,
        "effort": 355.03,
        "level": 0.18,
        "bugs": 0.02,
        "time": 20,
        "intelligentContent": 11.32,
        "number_operators": 6,
        "number_operands": 14,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 28,
        "lloc": 18,
        "mi": 99.28,
        "mIwoC": 59.33,
        "commentWeight": 39.96,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    }
];
